// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miehygvomicrufxmcyja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZWh5Z3ZvbWljcnVmeG1jeWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODcxODQsImV4cCI6MjA2MDY2MzE4NH0.ARSQej_UidsCruf8l7LU1g3A0uVlACtwWyBzGv8YSK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);